title = "Istani gitleaks config"

[rules]

# Allowlist placeholders
[[allowlist.regexes]]
description = "placeholder keys"
regex = '''(your_gemini_api_key|your_anthropic_api_key|your_openrouter_api_key)'''

