'use client';

import React from 'react';

/**
 * Repository Dashboard Component
 *
 * Example integration showing how to use the aggregated repository data
 * generated by scripts/aggregateRepos.js
 *
 * Usage:
 * 1. Run `npm run aggregate` to generate data/reposData.json
 * 2. Import this component in your page
 * 3. The component will display repository statistics and insights
 *
 * Note: This example uses dynamic import. For production, consider:
 * - Fetching data from an API endpoint
 * - Using Next.js server components
 * - Implementing data caching
 */

interface CommitData {
  sha: string;
  message: string;
  author: {
    name: string;
    email: string;
    date: string;
  };
  url: string;
}

interface IssueData {
  number: number;
  title: string;
  state: string;
  author: string;
  labels: string[];
  createdAt: string;
  url: string;
  isPullRequest: boolean;
}

interface RepoMetadata {
  name: string;
  fullName: string;
  description: string;
  url: string;
  language: string;
  stars: number;
  forks: number;
  openIssues: number;
  topics: string[];
}

interface Repository {
  repository: string;
  metadata: RepoMetadata;
  recentCommits: CommitData[];
  openIssues: IssueData[];
  aggregatedAt: string;
}

interface ReposData {
  generatedAt: string;
  totalRepositories: number;
  successfulAggregations: number;
  failedAggregations: number;
  repositories: Repository[];
}

export function RepositoryDashboard() {
  const [reposData, setReposData] = React.useState<ReposData | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    async function loadData() {
      try {
        // In production, fetch from an API endpoint instead
        const response = await fetch('/data/reposData.json');

        if (!response.ok) {
          throw new Error('Failed to load repository data');
        }

        const data = await response.json();
        setReposData(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Unknown error');
        console.error('Error loading repository data:', err);
      } finally {
        setLoading(false);
      }
    }

    loadData();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  if (error || !reposData) {
    return (
      <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
        <p className="text-red-800">
          Error loading repository data. Please run{' '}
          <code className="bg-red-100 px-2 py-1 rounded">npm run aggregate</code> first.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header Summary */}
      <div className="bg-white rounded-lg shadow p-6">
        <h2 className="text-2xl font-bold mb-4">Repository Overview</h2>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <StatCard label="Total Repositories" value={reposData.totalRepositories} icon="📦" />
          <StatCard label="Successful" value={reposData.successfulAggregations} icon="✅" />
          <StatCard label="Failed" value={reposData.failedAggregations} icon="❌" />
          <StatCard
            label="Total Stars"
            value={reposData.repositories.reduce((sum, r) => sum + r.metadata.stars, 0)}
            icon="⭐"
          />
        </div>
        <p className="text-sm text-gray-500 mt-4">
          Last updated: {new Date(reposData.generatedAt).toLocaleString()}
        </p>
      </div>

      {/* Repository Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reposData.repositories.map((repo) => (
          <RepositoryCard key={repo.repository} repo={repo} />
        ))}
      </div>
    </div>
  );
}

function StatCard({ label, value, icon }: { label: string; value: number; icon: string }) {
  return (
    <div className="bg-gray-50 rounded-lg p-4">
      <div className="flex items-center gap-2 mb-2">
        <span className="text-2xl">{icon}</span>
        <span className="text-sm font-medium text-gray-600">{label}</span>
      </div>
      <div className="text-3xl font-bold text-gray-900">{value.toLocaleString()}</div>
    </div>
  );
}

function RepositoryCard({ repo }: { repo: Repository }) {
  return (
    <div className="bg-white rounded-lg shadow hover:shadow-lg transition-shadow p-6">
      {/* Header */}
      <div className="mb-4">
        <a
          href={repo.metadata.url}
          target="_blank"
          rel="noopener noreferrer"
          className="text-xl font-bold text-blue-600 hover:text-blue-800 transition-colors"
        >
          {repo.metadata.name}
        </a>
        <p className="text-sm text-gray-600 mt-1 line-clamp-2">{repo.metadata.description}</p>
      </div>

      {/* Stats */}
      <div className="flex gap-4 mb-4 text-sm text-gray-600">
        <span>⭐ {repo.metadata.stars}</span>
        <span>🔱 {repo.metadata.forks}</span>
        <span>📝 {repo.metadata.openIssues}</span>
      </div>

      {/* Language */}
      {repo.metadata.language && (
        <div className="mb-4">
          <span className="inline-block bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded">
            {repo.metadata.language}
          </span>
        </div>
      )}

      {/* Topics */}
      {repo.metadata.topics.length > 0 && (
        <div className="mb-4 flex flex-wrap gap-1">
          {repo.metadata.topics.slice(0, 3).map((topic) => (
            <span
              key={topic}
              className="inline-block bg-gray-100 text-gray-700 text-xs px-2 py-1 rounded"
            >
              {topic}
            </span>
          ))}
          {repo.metadata.topics.length > 3 && (
            <span className="text-xs text-gray-500 px-2 py-1">
              +{repo.metadata.topics.length - 3} more
            </span>
          )}
        </div>
      )}

      {/* Recent Activity */}
      <div className="border-t pt-4">
        <div className="text-sm">
          <div className="flex items-center justify-between mb-2">
            <span className="font-medium text-gray-700">Recent Activity</span>
          </div>
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-gray-600">
              <span>💾</span>
              <span>{repo.recentCommits.length} recent commits</span>
            </div>
            <div className="flex items-center gap-2 text-gray-600">
              <span>🐛</span>
              <span>{repo.openIssues.length} open issues</span>
            </div>
          </div>
        </div>
      </div>

      {/* Latest Commit */}
      {repo.recentCommits.length > 0 && (
        <div className="border-t mt-4 pt-4">
          <p className="text-xs text-gray-500 mb-1">Latest commit:</p>
          <p className="text-sm text-gray-700 line-clamp-2">{repo.recentCommits[0].message}</p>
          <p className="text-xs text-gray-500 mt-1">
            by {repo.recentCommits[0].author.name} •{' '}
            {new Date(repo.recentCommits[0].author.date).toLocaleDateString()}
          </p>
        </div>
      )}
    </div>
  );
}

export default RepositoryDashboard;
