name: Merge PRs

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Merge approved PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list --state open --json number,statusCheckRollup --jq '.[] | select(.statusCheckRollup | all(.conclusion == "success")) | .number' | while read pr; do
            gh pr merge $pr --auto --squash
          done
