name: Merge PRs (Disabled)

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'This workflow is intentionally disabled to prevent automated merges.'
        required: false

permissions:
  contents: read
  pull-requests: read

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Show notice
        run: |
          echo 'Automated PR merging has been disabled.'
          echo 'Merge changes manually after reviewing CI results.'
