name: Multi-Agent Sequential Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  security:
    name: Security Agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt update && sudo apt install gh -y
      - run: cd agents && npm install
      - run: cd agents && node security-agent.js --pr=\${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.claude }}
      - uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: agents/security-report.json

  quality:
    name: Code Quality Agent
    runs-on: ubuntu-latest
    needs: [security]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt update && sudo apt install gh -y
      - run: npm ci || npm install
      - run: cd agents && npm install
      - run: cd agents && node code-quality-agent.js --pr=\${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.claude }}
      - uses: actions/upload-artifact@v4
        with:
          name: quality-report
          path: agents/quality-report.json

  testing:
    name: Test Agent
    runs-on: ubuntu-latest
    needs: [quality]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt update && sudo apt install gh -y
      - run: npm ci || npm install
      - run: cd agents && npm install
      - run: cd agents && node test-agent.js --pr=\${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.claude }}
      - uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: agents/test-report.json

  performance:
    name: Performance Agent
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt update && sudo apt install gh -y
      - run: npm ci || npm install
      - run: cd agents && npm install
      - run: cd agents && node performance-agent.js --pr=\${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.claude }}
      - uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: agents/performance-report.json

  docs:
    name: Documentation Agent
    runs-on: ubuntu-latest
    needs: [performance]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt update && sudo apt install gh -y
      - run: cd agents && npm install
      - run: cd agents && node documentation-agent.js --pr=\${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.claude }}
      - uses: actions/upload-artifact@v4
        with:
          name: docs-report
          path: agents/docs-report.json

  architecture:
    name: Architecture Agent
    runs-on: ubuntu-latest
    needs: [docs]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt update && sudo apt install gh -y
      - run: cd agents && npm install
      - run: cd agents && node architecture-agent.js --pr=\${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.claude }}
      - uses: actions/upload-artifact@v4
        with:
          name: architecture-report
          path: agents/architecture-report.json

  orchestrate:
    name: Orchestrator
    runs-on: ubuntu-latest
    needs: [security, quality, testing, performance, docs, architecture]
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt update && sudo apt install gh -y
      - run: cd agents && npm install
      - uses: actions/download-artifact@v4
        with:
          path: reports/
      - run: cd agents && node orchestrator.js --pr=\${{ github.event.pull_request.number }} --reports-dir=../reports/ --generate-summary
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.claude }}
      - run: gh pr comment \${{ github.event.pull_request.number }} --body-file agents/final-review-summary.md
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

  autofix:
    name: Auto-Fix
    runs-on: ubuntu-latest
    needs: [orchestrate]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: \${{ github.event.pull_request.head.ref }}
          token: \${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt update && sudo apt install gh -y
      - run: npm ci || npm install
      - run: cd agents && npm install
      - uses: actions/download-artifact@v4
        with:
          path: reports/
      - run: cd agents && node auto-fix-agent.js --pr=\${{ github.event.pull_request.number }} --reports-dir=../reports/ --apply-fixes
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.claude }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || (git commit -m "Auto-fix from agents" && git push)

  merge:
    name: Merge Decision
    runs-on: ubuntu-latest
    needs: [orchestrate, autofix]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt update && sudo apt install gh -y
      - run: cd agents && npm install
      - uses: actions/download-artifact@v4
        with:
          path: reports/
      - run: find reports -name orchestrator-summary.json -exec cp {} agents/ \; || true
      - run: cd agents && node merge-decision-agent.js --pr=\${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.claude }}
      - run: |
          if [ -f agents/merge-decision.json ]; then
            MERGE=\$(cat agents/merge-decision.json | grep -o '"shouldMerge":[^,}]*' | cut -d: -f2 | tr -d ' "')
            [ "\$MERGE" = "true" ] && gh pr merge \${{ github.event.pull_request.number }} --squash --auto || echo "Not merging"
          fi
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
