name: n8n Workflow Automation

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-n8n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup n8n automation
        run: |
          echo "Setting up n8n integration for istani.org"
          echo "Automated fitness workflows ready"
